language: python

cache:
  - pip
  - test_data

python:
  - "3.5"
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install netcdf4
  - pip install numba
  - pip install scipy

# Fetch test data, if not cached
before_script:
  - mkdir -p test_data
  - pushd test_data
  - test -f ocean_hgrid.nc || wget ftp://ftp.gfdl.noaa.gov/perm/Alistair.Adcroft/MOM6-testing/OM4_05/ocean_hgrid.nc
  - test -f ocean_static.nc || wget ftp://ftp.gfdl.noaa.gov/perm/Alistair.Adcroft/MOM6-testing/OM4_05/ocean_static.nc
  - test -f runoff.daitren.clim.10FEB2011.nc || wget http://data1.gfdl.noaa.gov/~nnz/mom4/COREv2/data_IAF/CORRECTED/calendar_years/runoff.daitren.clim.10FEB2011.nc
  - popd

script:
  - ./regrid_runoff.py --help
  - ./regrid_runoff.py test_data/ocean_hgrid.nc test_data/ocean_static.nc -m wet test_data/runoff.daitren.clim.10FEB2011.nc test.nc -p
  - md5sum test.nc
